todolist/urls.py
from django.conf.urls import url

from . import views

app_name = 'todolist' #namespace für <li><a href="{% url 'todolist:edit' todo.id %}">{{ question.question_text }}</a></li> in template

urlpatterns = [
    url(r'^$', views.index, name='index'), #/todolist/
    url(r'^sitenotice', views.sitenotice, name='sitenotice'),
    url(r'^howto', views.how_to, name='how_to'),
    url(r'^(?P<todo_id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^create',views.create,name='create'),
]

todosite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^todolist/', include('todolist.urls')),
    url(r'^admin/', admin.site.urls),
]

todolist/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Todo(models.Model):
    task = models.CharField(max_length=160)
    due_date = models.DateTimeField('date due') #optional human readable name
    completion = models.IntegerField(default=0,
                                     validators=[MaxValueValidator(100), #we can remove this. validation doesn't work that way. validation in forms.
                                                 MinValueValidator(0)]
                                     )

    def __str__(self):
        return self.task

todolist/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator

class TodoForm(forms.Form):
    task = forms.CharField(label='Task', max_length=160,widget=forms.TextInput(attrs={'class' : 'form-control'}))
    date = forms.DateTimeField(label='Due',widget=forms.TextInput(attrs={'class' : 'form-control'}),input_formats=['%Y-%m-%d %H:%M'])
    completion = forms.IntegerField(label="Completion",widget=forms.NumberInput(attrs={'class' : 'form-control','min':'0','max':"100"}),validators=[MaxValueValidator(100),
                                                 MinValueValidator(0)])


class DeleteForm(forms.Form):
    delete = forms.IntegerField()

todolist/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from todolist.models import Todo #import nicht vergessen
from django.template import loader
from django.http import Http404
from .forms import TodoForm, DeleteForm
from django import urls

def index(request):
    if request.method == "POST":
        form = DeleteForm(request.POST)
        if form.is_valid():
            delete_id = form.cleaned_data['delete']
            if Todo.objects.filter(pk=delete_id):
                todel = Todo.objects.get(pk=delete_id)
                todel.delete()
    todos = Todo.objects.all()
    template = loader.get_template('todolist/index.html')
    context = {
        'todos': todos,
    }
    return HttpResponse(template.render(context, request))  # kürzer möglich, aber vorerst so. kürzer: https://docs.djangoproject.com/en/1.10/intro/tutorial03/

def edit(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    input_error = False
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            todo.task = form.cleaned_data['task']
            todo.due_date = form.cleaned_data['date']
            todo.completion = form.cleaned_data['completion']
            todo.save()
            return HttpResponseRedirect(urls.reverse('todolist:index'))
        else:
            input_error = True

    edit_form = TodoForm(initial={ 'task': todo.task, 'date': todo.due_date.strftime('%Y-%m-%d %H:%M'), 'completion': todo.completion })
    return render(request, 'todolist/edit.html', { 'todo': todo, 'edit_form': edit_form, 'input_error':input_error })

def create(request):
    input_error = False
    if request.method == "POST":
        #compute data and either send to index or return error. maybe do this in index?
        form = TodoForm(request.POST)
        if form.is_valid():
            taskd = form.cleaned_data['task']
            dued = form.cleaned_data['date']
            completiond = form.cleaned_data['completion']
            newTodo= Todo(task= taskd, due_date= dued, completion=completiond)
            newTodo.save()
            return HttpResponseRedirect(urls.reverse('todolist:index'))
        else:
            input_error = True

    template = loader.get_template('todolist/create.html')
    form= TodoForm()    #neue todoform wird zur eingabe erstellt
    context = {
        'form': form,
        'input_error':input_error,
    }
    return HttpResponse(template.render(context, request))

def sitenotice(request):
    return render(request, 'todolist/sitenotice.html')

def how_to(request):
    return render(request, 'todolist/howto.html')

todolist/templates/todolist/create.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'todolist/style.css' %}" />

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Bootstrap 101 Template</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body style="padding-top: 60px;"> <!-- needs fix!!!-->
        {% include 'todolist/nav.html' with active="index" %}

        <div class="container">
            <form method="post" action="{% url 'todolist:create' %}"> <!-- /create/ ok. or with url?-->
                {% csrf_token %} <!-- meaning? -->
                {{form}}
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            {% if input_error %}
                {% include 'todolist/error.html' %}
            {% endif %}
        </div>
    </body>
</html>

todolist/templates/todolist/edit.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'todolist/style.css' %}" />

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Bootstrap 101 Template</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body style="padding-top: 60px;"> <!-- needs fix!!!-->
        {% include 'todolist/nav.html' with active="index" %}

        <div class="container">
            <form method="post" action="{% url 'todolist:edit' todo.id %}"> <!-- /create/ ok. or with url?-->
                {% csrf_token %}
                {{ edit_form }}
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            {% if input_error %}
                {% include 'todolist/error.html' %}
            {% endif %}
        </div>
    </body>
</html>

todolist/templates/todolist/error.html
<span class="label label-danger">Invalid input. Please try again (Check date format)</span>

todolist/templates/todolist/howto.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Bootstrap 101 Template</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <link rel="stylesheet" href="css/style.css">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        {% include 'todolist/nav.html' with active="how_to" %}

        <div class="container">
            <h2>How To add a TODO</h2>
            <p>To add a TODO, simply navigate to <em>Example list</em>
            and click <button type="submit" class="btn btn-lg btn-success centerbutton disabled" style="cursor:default;">
                Create New TODO</button> and a form will appear. Use this form, and the onscreen instructions to
            create your TODO.</p>
            <h2>How to edit a TODO</h2>
            <ol>
                <li>Navigate to the <em>Example list.</em></li>
                <li>Choose the TODO you want to edit and click the <button type="submit" class="btn btn-sm btn-info centerbutton disabled" style="cursor:default;">Edit</button> button.</li>
                <li>A form will appear, prompting you to enter new entry values. Simply follow the instructions        ODER:</li>
                <li>The title, progress and deadline fields will turn into forms, into which you'll be able to enter the updated information. Empty forms will not be persisted.</li>
                <li>If you change your mind, just click the Cancel button</li>
            </ol>
        </div>
    </body>
</html>

todolist/templates/todolist/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'todolist/style.css' %}" />

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Bootstrap 101 Template</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body style="padding-top: 60px;"> <!-- needs fix!!!-->
        <!--
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">My To-Do List</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a>Example list</a></li>
                        <li><a href="howto.html">How to</a></li>
                        <li><a href="sitenotice.html">Site notice</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        -->

        {% include 'todolist/nav.html' with active="index" %}

        <div class="container">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th class="col-md-8">Task</th>
                        <th class="col-md-4">Due</th>
                        <th class="col-md-2">Completion</th>
                        <th class="col-md-2"></th>
                        <th class="col-md-2"></th>
                    </tr>
                </thead>
                <!-- doppelte geschweifte klammern sind vars -->
                {% if todos %}
                <tbody>
                    {% for todo in todos %}
                    <tr>
                        <td>{{todo.id}}</td>
                        <td>{{todo.task}}</td>
                        <td>{{todo.due_date}}</td>
                        <td>{{todo.completion}}%</td>
                        <td>
                            <a href="{% url 'todolist:edit' todo_id=todo.id %}" class="btn btn-xs btn-info">Edit</a>
                        </td>
                        <td>
                            <form action= "{% url 'todolist:index' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="delete" value="{{todo.id}}"/>
                                <button type="submit" class="btn btn-xs btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr> 
                    {% endfor %}
                </tbody>
                {% else %}
                <p>No todos are available.</p>
                {% endif %}
            </table>
            <a href="{% url 'todolist:create' %}" class="btn btn-lg btn-success">Create New TODO</a> <!--aus http://stackoverflow.com/questions/2906582/how-to-create-an-html-button-that-acts-like-a-link  typ ist button und submit-->
    </body>
</html>

todolist/templates/todolist/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">My To-Do List</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li {% if active == "index" %} class="active" {% endif %}><a href="{% url 'todolist:index' %}">My Todos</a></li>
                <li {% if active == "how_to" %} class="active" {% endif %}><a href="{% url 'todolist:how_to' %}">How to</a></li>
                <li {% if active == "sitenotice" %} class="active" {% endif %}><a href="{% url 'todolist:sitenotice' %}">Site notice</a></li>
            </ul>
        </div>
    </div>
</nav>

todolist/templates/todolist/sitenotice.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        {% load staticfiles %}
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Bootstrap 101 Template</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <link rel="stylesheet" href="css/style.css">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body style="padding-top: 60px;">
        {% include 'todolist/nav.html' with active="sitenotice" %}

        <div class="container">
            <h1 class="header centertext"> The Crew </h1>

            <div class="row">
                <div class="col-sm-4">
                    <h2>Alex</h2>
                    <img data-src="holder.js/200x200" alt="200x200" style="width: 200px; height: 200px;" src="{% static 'todolist/img/dog1.jpg' %}" data-holder-rendered="true">
                    <p>Wuff Wuff </p>
                </div>
                <div class="col-sm-4">
                    <h2>Jessica</h2>
                    <img data-src="holder.js/200x200" alt="200x200" style="width: 200px; height: 200px;" src="{% static 'todolist/img/dog2.jpg' %}" data-holder-rendered="true">
                    <p>Bork Bork </p>
                </div>
                <div class="col-sm-4">
                    <h2>Nils</h2>
                    <img data-src="holder.js/200x200" alt="200x200" style="width: 200px; height: 200px;" src="{% static 'todolist/img/dog3.jpg' %}" data-holder-rendered="true">
                    <p>Ruff Ruff</p>
                </div>
            </div>
        </div>
    </body>
</html>